name: 'Code Reviewer Action'
description: 'Reviews and comments pull requests using LLMs like Claude or GPT'
author: 'Squad-C'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
