name: 'Code Reviewer Action'
description: 'Reviews and comments pull requests using LLMs like Claude or GPT'
author: 'The Famous Cat Ltd.'

# Define your inputs here.
inputs:
    GITHUB_TOKEN:
        description: 'GitHub token to interact with the repository.'
        required: true
    API_KEY:
        required: true
    exclude:
        description: 'Glob patterns to exclude files from the diff analysis'
        required: false
        default: ''
    include:
        description: 'Glob patterns to include files from the diff analysis'
        required: false
        default: '**/**'
    review_comments:
        required: false
        default: false
    review_codestyle:
        required: false
        default: false
    review_readability:
        required: false
        default: false
    review_naming:
        required: false
        default: false
    review_tests:
        required: false
        default: false

runs:
    using: node20
    main: dist/index.js
