name: Automatic LLM Code Review
on:
    pull_request:
        types:
            - opened
            - synchronize
permissions: write-all
jobs:
    code_review:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Code Review
              id: review
              uses: ./
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
                  LLM_MODEL: 'claude-3-haiku-20240307'
                  exclude: 'yarn.lock,dist/**'
                  include: 'src/**'
                  dry-run: false
            - name: Debug Prompts
              run: |
                  echo "${{ steps.review.outputs.prompts }}"
            - name: Debug Comments
              run: |
                  echo "${{ steps.review.outputs.comments }}"
